export const pokemons = [
	{
		id: '1011',
		name: 'Caterpie',
		classification: 'Worm',
		number: '1',
		fleeRate: '6.4 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/10.png',
	},
	{
		id: '91111',
		name: 'Blastoise',
		classification: 'Shellfish',
		number: '503',
		fleeRate: '188.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/9-mega.png',
	},
	{
		id: '844',
		name: 'Wartortle',
		classification: 'Turtle',
		number: '303',
		fleeRate: '49.6 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/8.png',
	},
	{
		id: '7555',
		name: 'Squirtle',
		classification: 'Tiny Turtle',
		number: '10',
		fleeRate: '19.8 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/7.png',
	},
	{
		id: '66565',
		name: 'Charizard',
		classification: 'Flame',
		number: '50',
		fleeRate: '199.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/6.png',
	},
	{
		id: '56565',
		name: 'Charmeleon',
		classification: 'Flame',
		number: '37',
		fleeRate: '41.9 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/5.png',
	},
	{
		id: '45645',
		name: 'Charmander',
		classification: 'Lizard',
		number: '2',
		fleeRate: '18.7 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/4.png',
	},
	{
		id: '3468',
		name: 'Venusaur',
		classification: 'Seed',
		number: '607',
		fleeRate: '220.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/3.png',
	},
	{
		id: '54352',
		name: 'Ivysaur',
		classification: 'Seed',
		number: '3',
		fleeRate: '28.7 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/2.png',
	},
	{
		id: '1543430',
		name: 'Caterpie',
		classification: 'Worm',
		number: '1',
		fleeRate: '6.4 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/10.png',
	},
	{
		id: '78679',
		name: 'Blastoise',
		classification: 'Shellfish',
		number: '5',
		fleeRate: '188.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/9-mega.png',
	},
	{
		id: '88786',
		name: 'Wartortle',
		classification: 'Turtle',
		number: '303',
		fleeRate: '49.6 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/8.png',
	},
	{
		id: '7786763',
		name: 'Squirtle',
		classification: 'Tiny Turtle',
		number: '108',
		fleeRate: '19.8 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/7.png',
	},
	{
		id: '687676786',
		name: 'Charizard',
		classification: 'Flame',
		number: '507',
		fleeRate: '199.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/6.png',
	},
	{
		id: '58767868763',
		name: 'Charmeleon',
		classification: 'Flame',
		number: '307"',
		fleeRate: '41.9 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/5.png',
	},
	{
		id: '876786784',
		name: 'Charmander',
		classification: 'Lizard',
		number: '2',
		fleeRate: '18.7 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/4.png',
	},
	{
		id: '7867868763',
		name: 'Venusaur',
		classification: 'Seed',
		number: '607',
		fleeRate: '220.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/3.png',
	},
	{
		id: '287678676',
		name: 'Ivysaur',
		classification: 'Seed',
		number: '303',
		fleeRate: '28.7 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/2.png',
	},
	{
		id: '10867867',
		name: 'Caterpie',
		classification: 'Worm',
		number: '1',
		fleeRate: '6.4 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/10.png',
	},
	{
		id: '876889',
		name: 'Blastoise',
		classification: 'Shellfish',
		number: '503"',
		fleeRate: '188.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/9-mega.png',
	},
	{
		id: '88888',
		name: 'Wartortle',
		classification: 'Turtle',
		number: '303"',
		fleeRate: '49.6 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/8.png',
	},
	{
		id: '55557',
		name: 'Squirtle',
		classification: 'Tiny Turtle',
		number: '108',
		fleeRate: '19.8 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/7.png',
	},
	{
		id: '44446',
		name: 'Charizard',
		classification: 'Flame',
		number: '507',
		fleeRate: '199.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/6.png',
	},
	{
		id: '9995',
		name: 'Charmeleon',
		classification: 'Flame',
		number: '307',
		fleeRate: '41.9 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/5.png',
	},
	{
		id: '4',
		name: 'Charmander',
		classification: 'Lizard',
		number: '2',
		fleeRate: '18.7 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/4.png',
	},
	{
		id: '88887773',
		name: 'Venusaur',
		classification: 'Seed',
		number: '607',
		fleeRate: '220.5 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/3.png',
	},
	{
		id: '29999',
		name: 'Ivysaur',
		classification: 'Seed',
		number: '303',
		fleeRate: '28.7 lbs.',
		image: 'https://cdn.traction.one/pokedex/pokemon/2.png',
	},
]
